package net.bingyan.xuyu.domain;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.writer
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer writer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.moment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer momentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.interlocutor
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer interlocutor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.time
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.content
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.comment_id
	 * @return  the value of comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getCommentId()
	{
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.comment_id
	 * @param commentId  the value for comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setCommentId(Integer commentId)
	{
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.writer
	 * @return  the value of comments.writer
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getWriter()
	{
		return writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.writer
	 * @param writer  the value for comments.writer
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setWriter(Integer writer)
	{
		this.writer = writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.moment_id
	 * @return  the value of comments.moment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getMomentId()
	{
		return momentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.moment_id
	 * @param momentId  the value for comments.moment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setMomentId(Integer momentId)
	{
		this.momentId = momentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.interlocutor
	 * @return  the value of comments.interlocutor
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getInterlocutor()
	{
		return interlocutor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.interlocutor
	 * @param interlocutor  the value for comments.interlocutor
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setInterlocutor(Integer interlocutor)
	{
		this.interlocutor = interlocutor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.time
	 * @return  the value of comments.time
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Date getTime()
	{
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.time
	 * @param time  the value for comments.time
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setTime(Date time)
	{
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.content
	 * @return  the value of comments.content
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.content
	 * @param content  the value for comments.content
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setContent(String content)
	{
		this.content = content == null ? null : content.trim();
	}
}