package net.bingyan.xuyu.domain;

public class Moment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column moment.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	private Integer momentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column moment.user_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column moment.movie
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	private String movie;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column moment.moment_id
	 * @return  the value of moment.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public Integer getMomentId() {
		return momentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column moment.moment_id
	 * @param momentId  the value for moment.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public void setMomentId(Integer momentId) {
		this.momentId = momentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column moment.user_id
	 * @return  the value of moment.user_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column moment.user_id
	 * @param userId  the value for moment.user_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column moment.movie
	 * @return  the value of moment.movie
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public String getMovie() {
		return movie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column moment.movie
	 * @param movie  the value for moment.movie
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public void setMovie(String movie) {
		this.movie = movie == null ? null : movie.trim();
	}
}