package net.bingyan.xuyu.domain;

public class MomentPhoto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column moment_photo.id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column moment_photo.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	private Integer momentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column moment_photo.id
	 * @return  the value of moment_photo.id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column moment_photo.id
	 * @param id  the value for moment_photo.id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column moment_photo.moment_id
	 * @return  the value of moment_photo.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public Integer getMomentId() {
		return momentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column moment_photo.moment_id
	 * @param momentId  the value for moment_photo.moment_id
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	public void setMomentId(Integer momentId) {
		this.momentId = momentId;
	}
}