package net.bingyan.xuyu.domain;

public class UserAgreeComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_agree_comments.user_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_agree_comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	private Integer commentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_agree_comments.user_id
	 * @return  the value of users_agree_comments.user_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getUserId()
	{
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_agree_comments.user_id
	 * @param userId  the value for users_agree_comments.user_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_agree_comments.comment_id
	 * @return  the value of users_agree_comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public Integer getCommentId()
	{
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_agree_comments.comment_id
	 * @param commentId  the value for users_agree_comments.comment_id
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	public void setCommentId(Integer commentId)
	{
		this.commentId = commentId;
	}
}