package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.Comment;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	Comment selectByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	List<Comment> selectAll();
}