package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.MomentPhoto;

public interface MomentPhotoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment_photo
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment_photo
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int insert(MomentPhoto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment_photo
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	MomentPhoto selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment_photo
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	List<MomentPhoto> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment_photo
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int updateByPrimaryKey(MomentPhoto record);
}