package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.Moment;

public interface MomentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int deleteByPrimaryKey(Integer momentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int insert(Moment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	Moment selectByPrimaryKey(Integer momentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	List<Moment> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table moment
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int updateByPrimaryKey(Moment record);
}