package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.UserAgreeComment;
import org.apache.ibatis.annotations.Param;

public interface UserAgreeCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_agree_comments
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("commentId") Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_agree_comments
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int insert(UserAgreeComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_agree_comments
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	List<UserAgreeComment> selectAll();
}