package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Nov 06 19:20:42 CST 2016
	 */
	int updateByPrimaryKey(User record);
}