package net.bingyan.xuyu.mapper;

import java.util.List;
import net.bingyan.xuyu.domain.UserFavoriteMoment;
import org.apache.ibatis.annotations.Param;

public interface UserFavoriteMomentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_favorite_moment
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("momentId") Integer momentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_favorite_moment
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	int insert(UserFavoriteMoment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_favorite_moment
	 * @mbg.generated  Mon Nov 07 21:36:37 CST 2016
	 */
	List<UserFavoriteMoment> selectAll();
}